services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on localhost:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # MongoDB admin username
      MONGO_INITDB_ROOT_PASSWORD: password # MongoDB admin password

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081" # Expose Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin # Must match MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: password # Must match MongoDB admin password
      ME_CONFIG_MONGODB_SERVER: mongodb # Name of the MongoDB service